import json
import math
from datetime import date, datetime
from typing import Any

from config.configuration import ADULTS, ALLOW_SCHEMA_REBUILD, CHILDREN, ROOMS
from config.database import database_url, ensure_database_exists, psycopg
from utils.helpers import parse_date


ReviewIncrementState = dict[str, Any]


def db_value(value: Any) -> Any:
    if value is None:
        return None
    try:
        if value is not value:
            return None
    except Exception:
        pass
    if isinstance(value, float) and math.isnan(value):
        return None
    if value in ("", [], {}):
        return None
    if isinstance(value, (dict, list, tuple)):
        return json.dumps(value, ensure_ascii=False)
    return value


def text_limit(value: Any, max_length: int) -> str | None:
    cleaned = db_value(value)
    if cleaned is None:
        return None
    text = str(cleaned).strip()
    if not text:
        return None
    return text[:max_length]


def date_value(value: Any) -> date | None:
    return parse_date(value)


def bool_value(value: Any) -> bool | None:
    if value in (None, ""):
        return None
    return bool(value)


def int_value(value: Any) -> int | None:
    if value in (None, ""):
        return None
    try:
        return int(float(value))
    except (TypeError, ValueError):
        return None


def bounded_int_value(
    value: Any,
    minimum: int | None = None,
    maximum: int | None = None,
) -> int | None:
    number = int_value(value)
    if number is None:
        return None
    if minimum is not None and number < minimum:
        return None
    if maximum is not None and number > maximum:
        return None
    return number


def numeric_value(value: Any) -> float | None:
    if value in (None, ""):
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def bounded_numeric_value(
    value: Any,
    minimum: float | None = None,
    maximum: float | None = None,
) -> float | None:
    number = numeric_value(value)
    if number is None:
        return None
    if minimum is not None and number < minimum:
        return None
    if maximum is not None and number > maximum:
        return None
    return number


def time_value(value: Any) -> str | None:
    if value in (None, ""):
        return None
    text = str(value)
    import re

    match = re.search(r"([0-2]?\d:[0-5]\d)", text)
    if not match:
        return None
    return match.group(1)


def currency_code(value: Any) -> str | None:
    if value in (None, ""):
        return None
    text = str(value).strip().upper()
    return text[:3] if text else None


def create_database_tables(connection: Any) -> None:
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT data_type
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = 'sources'
              AND column_name = 'source_id'
            """
        )
        existing_source_id_type = cursor.fetchone()
        if existing_source_id_type and existing_source_id_type[0] not in ("bigint",):
            if not ALLOW_SCHEMA_REBUILD:
                raise RuntimeError(
                    "Existing prototype schema detected, but automatic schema rebuild "
                    "is disabled. Set ALLOW_SCHEMA_REBUILD=true in .env only when "
                    "you intentionally want to drop and rebuild the old schema."
                )
            print("Existing prototype schema detected. Rebuilding standardized schema.")
            cursor.execute(
                """
                DROP TABLE IF EXISTS
                    offer_cancellation_rules,
                    availability_offers,
                    review_responses,
                    review_category_scores,
                    reviews,
                    reviewers,
                    images,
                    room_amenities,
                    place_source_amenities,
                    rate_plans,
                    room_types,
                    accommodation_source_details,
                    place_policies,
                    attractions,
                    accommodations,
                    amenities,
                    place_source_records,
                    places,
                    scraping_logs,
                    scraping_runs,
                    currencies,
                    locations,
                    place_types,
                    sources
                CASCADE
                """
            )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS sources (
                source_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                source_name VARCHAR(100) NOT NULL,
                source_code VARCHAR(30) NOT NULL UNIQUE,
                base_url TEXT,
                source_type VARCHAR(50),
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS place_types (
                place_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                type_name VARCHAR(150) NOT NULL,
                type_group VARCHAR(50) NOT NULL,
                description TEXT,
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE (type_group, type_name)
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS locations (
                location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                parent_location_id BIGINT REFERENCES locations(location_id),
                location_name VARCHAR(200) NOT NULL,
                location_type VARCHAR(50),
                country_code CHAR(2),
                region_name VARCHAR(150),
                district_name VARCHAR(150),
                latitude NUMERIC(10,7),
                longitude NUMERIC(10,7),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE NULLS NOT DISTINCT (parent_location_id, location_name, location_type)
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS currencies (
                currency_code CHAR(3) PRIMARY KEY,
                currency_name VARCHAR(100),
                symbol VARCHAR(10),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS amenities (
                amenity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                amenity_name VARCHAR(200) NOT NULL,
                amenity_category VARCHAR(100),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE (amenity_name, amenity_category)
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS scraping_runs (
                scraping_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                source_id BIGINT NOT NULL REFERENCES sources(source_id),
                run_type VARCHAR(50) NOT NULL,
                status VARCHAR(30) NOT NULL,
                started_at TIMESTAMPTZ NOT NULL,
                completed_at TIMESTAMPTZ,
                pages_total INTEGER NOT NULL DEFAULT 0,
                pages_success INTEGER NOT NULL DEFAULT 0,
                pages_failed INTEGER NOT NULL DEFAULT 0,
                errors_count INTEGER NOT NULL DEFAULT 0,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS scraping_logs (
                log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                scraping_run_id BIGINT NOT NULL REFERENCES scraping_runs(scraping_run_id),
                log_level VARCHAR(20),
                message TEXT,
                endpoint_url TEXT,
                http_method VARCHAR(10),
                http_status SMALLINT,
                duration_ms INTEGER,
                request_payload JSONB,
                response_payload JSONB,
                error_message TEXT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS places (
                place_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                place_type_id BIGINT NOT NULL REFERENCES place_types(place_type_id),
                location_id BIGINT REFERENCES locations(location_id),
                canonical_name VARCHAR(500) NOT NULL,
                short_description TEXT,
                geom TEXT,
                address TEXT,
                phone VARCHAR(50),
                email VARCHAR(320),
                website TEXT,
                booking_url TEXT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE (place_type_id, location_id, canonical_name)
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS place_source_records (
                place_source_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                place_id BIGINT NOT NULL REFERENCES places(place_id),
                source_id BIGINT NOT NULL REFERENCES sources(source_id),
                source_place_id VARCHAR(150) NOT NULL,
                source_url TEXT,
                source_name VARCHAR(500),
                source_category VARCHAR(150),
                latitude NUMERIC(10,7),
                longitude NUMERIC(10,7),
                star_rating NUMERIC(2,1),
                review_score NUMERIC(4,2),
                review_count INTEGER NOT NULL DEFAULT 0,
                ranking_position INTEGER,
                popularity_score NUMERIC(10,4),
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                first_scraped_at TIMESTAMPTZ,
                last_scraped_at TIMESTAMPTZ,
                raw_json JSONB,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE (source_id, source_place_id)
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS accommodation_source_details (
                detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                place_source_id BIGINT NOT NULL UNIQUE REFERENCES place_source_records(place_source_id),
                checkin_from TIME,
                checkin_until TIME,
                checkout_from TIME,
                checkout_until TIME,
                pets_allowed BOOLEAN,
                children_allowed BOOLEAN,
                beachfront BOOLEAN,
                distance_to_beach_m INTEGER,
                license_number VARCHAR(150),
                languages_spoken TEXT,
                airport_shuttle BOOLEAN,
                parking_available BOOLEAN,
                breakfast_available BOOLEAN,
                breakfast_type VARCHAR(150),
                property_class VARCHAR(100),
                year_opened SMALLINT,
                year_renovated SMALLINT,
                chain_name VARCHAR(200),
                raw_json JSONB,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS attraction_source_details (
                detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                place_source_id BIGINT NOT NULL UNIQUE REFERENCES place_source_records(place_source_id),
                attraction_category VARCHAR(200),
                attraction_subcategory VARCHAR(200),
                recommended_duration TEXT,
                duration_minutes INTEGER,
                ticket_required BOOLEAN,
                booking_available BOOLEAN,
                price_from NUMERIC(14,2),
                currency_code CHAR(3) REFERENCES currencies(currency_code),
                family_friendly BOOLEAN,
                accessibility_info TEXT,
                raw_json JSONB,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS restaurant_source_details (
                detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                place_source_id BIGINT NOT NULL UNIQUE REFERENCES place_source_records(place_source_id),
                price_range VARCHAR(100),
                reservation_available BOOLEAN,
                delivery_available BOOLEAN,
                takeaway_available BOOLEAN,
                seating_available BOOLEAN,
                outdoor_seating BOOLEAN,
                raw_json JSONB,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS operating_hours (
                operating_hour_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                place_source_id BIGINT NOT NULL REFERENCES place_source_records(place_source_id),
                day_of_week SMALLINT NOT NULL,
                open_time TIME,
                close_time TIME,
                is_closed BOOLEAN NOT NULL DEFAULT FALSE,
                is_24_hours BOOLEAN NOT NULL DEFAULT FALSE,
                raw_text TEXT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE (place_source_id, day_of_week)
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS room_types (
                room_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                place_source_id BIGINT NOT NULL REFERENCES place_source_records(place_source_id),
                source_room_id VARCHAR(150),
                room_name VARCHAR(300) NOT NULL,
                room_code VARCHAR(100),
                max_occupancy SMALLINT,
                max_adults SMALLINT,
                max_children SMALLINT,
                max_child_age TEXT,
                bed_configuration SMALLINT,
                bedrooms_count SMALLINT,
                size_sqm NUMERIC(8,2),
                balcony BOOLEAN,
                view_type VARCHAR(150),
                air_conditioning BOOLEAN,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE (place_source_id, source_room_id)
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS rate_plans (
                rate_plan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                place_source_id BIGINT NOT NULL REFERENCES place_source_records(place_source_id),
                rate_plan_code VARCHAR(150),
                rate_plan_name VARCHAR(100),
                meal_plan VARCHAR(100),
                breakfast_included BOOLEAN,
                free_cancellation BOOLEAN,
                refundable BOOLEAN,
                includes_taxes BOOLEAN,
                min_stay SMALLINT,
                max_stay SMALLINT,
                prepayment_type VARCHAR(100),
                pay_at_property BOOLEAN,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE (place_source_id, rate_plan_code)
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS place_source_amenities (
                place_source_id BIGINT NOT NULL REFERENCES place_source_records(place_source_id),
                amenity_id BIGINT NOT NULL REFERENCES amenities(amenity_id),
                is_available BOOLEAN NOT NULL DEFAULT TRUE,
                additional_info TEXT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (place_source_id, amenity_id)
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS room_amenities (
                room_type_id BIGINT NOT NULL REFERENCES room_types(room_type_id),
                amenity_id BIGINT NOT NULL REFERENCES amenities(amenity_id),
                is_available BOOLEAN NOT NULL DEFAULT TRUE,
                additional_info TEXT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (room_type_id, amenity_id)
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS images (
                image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                place_source_id BIGINT NOT NULL REFERENCES place_source_records(place_source_id),
                room_type_id BIGINT REFERENCES room_types(room_type_id),
                image_url TEXT NOT NULL,
                thumbnail_url TEXT,
                image_type VARCHAR(100),
                caption TEXT,
                display_order SMALLINT,
                is_primary BOOLEAN NOT NULL DEFAULT FALSE,
                width_pixels INTEGER,
                height_pixels INTEGER,
                image_hash VARCHAR(128),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE (place_source_id, image_hash)
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS reviewers (
                reviewer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                source_id BIGINT NOT NULL REFERENCES sources(source_id),
                source_reviewer_id VARCHAR(150) NOT NULL,
                reviewer_name VARCHAR(200),
                country_code CHAR(2),
                reviewer_level VARCHAR(100),
                profile_image_url TEXT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE NULLS NOT DISTINCT (source_id, source_reviewer_id)
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS reviews (
                review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                place_source_id BIGINT NOT NULL REFERENCES place_source_records(place_source_id),
                reviewer_id BIGINT REFERENCES reviewers(reviewer_id),
                room_type_id BIGINT REFERENCES room_types(room_type_id),
                source_review_id VARCHAR(150) NOT NULL,
                review_title TEXT,
                review_text TEXT,
                positive_text TEXT,
                negative_text TEXT,
                review_score NUMERIC(4,2),
                travel_type VARCHAR(100),
                stay_length SMALLINT,
                country_code CHAR(2),
                room_name VARCHAR(300),
                visit_date DATE,
                review_date DATE NOT NULL,
                verified_stay BOOLEAN,
                helpful_votes INTEGER NOT NULL DEFAULT 0,
                language_code VARCHAR(20),
                raw_json JSONB,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE (place_source_id, source_review_id)
            )
            """
        )
        cursor.execute("ALTER TABLE reviews ADD COLUMN IF NOT EXISTS raw_json JSONB")
        cursor.execute("ALTER TABLE places ADD COLUMN IF NOT EXISTS latitude NUMERIC(10,7)")
        cursor.execute("ALTER TABLE places ADD COLUMN IF NOT EXISTS longitude NUMERIC(10,7)")
        cursor.execute("ALTER TABLE places ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE")
        cursor.execute("ALTER TABLE place_source_records ADD COLUMN IF NOT EXISTS ranking_total INTEGER")
        cursor.execute("ALTER TABLE place_source_records ADD COLUMN IF NOT EXISTS ranking_text TEXT")
        cursor.execute("ALTER TABLE place_source_records ADD COLUMN IF NOT EXISTS ranking_category VARCHAR(200)")
        cursor.execute("ALTER TABLE accommodation_source_details ADD COLUMN IF NOT EXISTS checkin_until TIME")
        cursor.execute("ALTER TABLE accommodation_source_details ADD COLUMN IF NOT EXISTS checkout_from TIME")
        cursor.execute("ALTER TABLE accommodation_source_details ADD COLUMN IF NOT EXISTS breakfast_available BOOLEAN")
        cursor.execute("ALTER TABLE accommodation_source_details ADD COLUMN IF NOT EXISTS property_class VARCHAR(100)")
        cursor.execute("ALTER TABLE accommodation_source_details ADD COLUMN IF NOT EXISTS raw_json JSONB")
        cursor.execute("ALTER TABLE place_source_amenities ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ")
        cursor.execute("ALTER TABLE images ADD COLUMN IF NOT EXISTS source_image_id VARCHAR(150)")
        cursor.execute("ALTER TABLE images ADD COLUMN IF NOT EXISTS raw_json JSONB")
        cursor.execute("ALTER TABLE reviewers ALTER COLUMN source_reviewer_id DROP NOT NULL")
        cursor.execute("ALTER TABLE reviewers ADD COLUMN IF NOT EXISTS username VARCHAR(200)")
        cursor.execute("ALTER TABLE reviewers ADD COLUMN IF NOT EXISTS country_name VARCHAR(150)")
        cursor.execute("ALTER TABLE reviewers ADD COLUMN IF NOT EXISTS profile_url TEXT")
        cursor.execute("ALTER TABLE reviewers ADD COLUMN IF NOT EXISTS contribution_count INTEGER")
        cursor.execute("ALTER TABLE reviewers ADD COLUMN IF NOT EXISTS helpful_vote_count INTEGER")
        cursor.execute("ALTER TABLE reviewers ADD COLUMN IF NOT EXISTS raw_json JSONB")
        cursor.execute("ALTER TABLE reviews ALTER COLUMN source_review_id DROP NOT NULL")
        cursor.execute("ALTER TABLE reviews ALTER COLUMN review_date DROP NOT NULL")
        cursor.execute("ALTER TABLE reviews ADD COLUMN IF NOT EXISTS rating_scale NUMERIC(4,2)")
        cursor.execute("ALTER TABLE reviews ADD COLUMN IF NOT EXISTS stay_date DATE")
        cursor.execute("ALTER TABLE reviews ADD COLUMN IF NOT EXISTS trip_type VARCHAR(100)")
        cursor.execute("ALTER TABLE reviews ADD COLUMN IF NOT EXISTS original_language_code VARCHAR(20)")
        cursor.execute("ALTER TABLE reviews ADD COLUMN IF NOT EXISTS is_machine_translated BOOLEAN")
        cursor.execute("ALTER TABLE reviews ADD COLUMN IF NOT EXISTS is_verified BOOLEAN")
        cursor.execute("ALTER TABLE reviews ADD COLUMN IF NOT EXISTS source_url TEXT")
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS review_category_scores (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                review_id BIGINT NOT NULL REFERENCES reviews(review_id),
                category_name VARCHAR(100) NOT NULL,
                score NUMERIC(4,2) NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE (review_id, category_name)
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS review_responses (
                response_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                review_id BIGINT NOT NULL REFERENCES reviews(review_id),
                source_response_id VARCHAR(150),
                responder_name VARCHAR(200),
                responder_role VARCHAR(100),
                response_text TEXT NOT NULL,
                response_date DATE,
                raw_json JSONB,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE NULLS NOT DISTINCT (review_id, source_response_id)
            )
            """
        )
        cursor.execute("ALTER TABLE review_responses ADD COLUMN IF NOT EXISTS raw_json JSONB")
        cursor.execute("ALTER TABLE review_category_scores ADD COLUMN IF NOT EXISTS rating_scale NUMERIC(4,2)")
        cursor.execute("ALTER TABLE scraping_runs ADD COLUMN IF NOT EXISTS entity_type VARCHAR(100)")
        cursor.execute("ALTER TABLE scraping_runs ADD COLUMN IF NOT EXISTS records_found INTEGER")
        cursor.execute("ALTER TABLE scraping_runs ADD COLUMN IF NOT EXISTS records_new INTEGER")
        cursor.execute("ALTER TABLE scraping_runs ADD COLUMN IF NOT EXISTS records_updated INTEGER")
        cursor.execute("ALTER TABLE scraping_runs ADD COLUMN IF NOT EXISTS pages_successful INTEGER")
        cursor.execute("ALTER TABLE scraping_runs ADD COLUMN IF NOT EXISTS stop_reason TEXT")
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS availability_offers (
                offer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                place_source_id BIGINT NOT NULL REFERENCES place_source_records(place_source_id),
                room_type_id BIGINT REFERENCES room_types(room_type_id),
                rate_plan_id BIGINT REFERENCES rate_plans(rate_plan_id),
                checkin_date DATE NOT NULL,
                checkout_date DATE NOT NULL,
                nights SMALLINT NOT NULL,
                adults SMALLINT NOT NULL,
                children SMALLINT NOT NULL,
                rooms_requested SMALLINT NOT NULL,
                currency_code CHAR(3) REFERENCES currencies(currency_code),
                original_price NUMERIC(14,2),
                final_price NUMERIC(14,2),
                taxes_fees_amount NUMERIC(14,2),
                discount_amount NUMERIC(14,2),
                available BOOLEAN NOT NULL,
                scraped_at TIMESTAMPTZ NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS offer_cancellation_rules (
                rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                offer_id BIGINT NOT NULL REFERENCES availability_offers(offer_id),
                rule_order SMALLINT NOT NULL,
                cancellation_type VARCHAR(100),
                deadline_at TIMESTAMPTZ,
                penalty_type VARCHAR(50),
                penalty_amount NUMERIC(14,2),
                penalty_percent NUMERIC(5,2),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS place_policies (
                policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                place_source_id BIGINT NOT NULL REFERENCES place_source_records(place_source_id),
                policy_type VARCHAR(100) NOT NULL,
                policy_text TEXT,
                policy_value JSONB,
                effective_from DATE,
                effective_to DATE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
        cursor.execute("ALTER TABLE place_policies ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_places_location ON places(location_id)")
        cursor.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_sources_source_name_unique ON sources(source_name)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_source_records_source ON place_source_records(source_id)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_source_records_source_place ON place_source_records(source_id, source_place_id)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_reviewers_source_reviewer ON reviewers(source_id, source_reviewer_id)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_reviews_source_record ON reviews(place_source_id)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_reviews_source_review ON reviews(source_review_id)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_reviews_date ON reviews(review_date)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_review_category_scores_review ON review_category_scores(review_id)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_review_responses_review ON review_responses(review_id)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_scraping_runs_source_entity_started ON scraping_runs(source_id, entity_type, started_at)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_locations_country_code ON locations(country_code)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_offers_checkin ON availability_offers(checkin_date)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_offers_scraped_at ON availability_offers(scraped_at)")


def fetch_one_id(cursor: Any, query: str, params: tuple[Any, ...]) -> int:
    cursor.execute(query, params)
    row = cursor.fetchone()
    if row is None:
        raise RuntimeError("Expected database row was not returned.")
    return int(row[0])


def upsert_source(cursor: Any, row: dict) -> int:
    return fetch_one_id(
        cursor,
        """
        INSERT INTO sources (source_name, source_code, base_url, source_type, is_active, created_at, updated_at)
        VALUES (%s, %s, %s, %s, COALESCE(%s, TRUE), COALESCE(%s, NOW()), COALESCE(%s, NOW()))
        ON CONFLICT (source_code) DO UPDATE SET
            source_name = EXCLUDED.source_name,
            base_url = EXCLUDED.base_url,
            source_type = EXCLUDED.source_type,
            is_active = EXCLUDED.is_active,
            updated_at = NOW()
        RETURNING source_id
        """,
        (
            row.get("source_name"),
            row.get("source_code"),
            row.get("base_url"),
            row.get("source_type"),
            row.get("is_active"),
            row.get("created_at"),
            row.get("updated_at"),
        ),
    )


def upsert_place_type(cursor: Any, row: dict) -> int:
    return fetch_one_id(
        cursor,
        """
        INSERT INTO place_types (type_name, type_group, description, is_active, created_at, updated_at)
        VALUES (%s, %s, %s, COALESCE(%s, TRUE), COALESCE(%s, NOW()), COALESCE(%s, NOW()))
        ON CONFLICT (type_group, type_name) DO UPDATE SET
            description = EXCLUDED.description,
            is_active = EXCLUDED.is_active,
            updated_at = NOW()
        RETURNING place_type_id
        """,
        (
            row.get("type_name"),
            row.get("type_group"),
            row.get("description"),
            row.get("is_active"),
            row.get("created_at"),
            row.get("updated_at"),
        ),
    )


def upsert_location(cursor: Any, row: dict, parent_id: int | None) -> int:
    return fetch_one_id(
        cursor,
        """
        INSERT INTO locations (
            parent_location_id, location_name, location_type, country_code,
            region_name, district_name, latitude, longitude, created_at, updated_at
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, COALESCE(%s, NOW()), COALESCE(%s, NOW()))
        ON CONFLICT (parent_location_id, location_name, location_type) DO UPDATE SET
            country_code = EXCLUDED.country_code,
            region_name = EXCLUDED.region_name,
            district_name = EXCLUDED.district_name,
            latitude = EXCLUDED.latitude,
            longitude = EXCLUDED.longitude,
            updated_at = NOW()
        RETURNING location_id
        """,
        (
            parent_id,
            row.get("location_name"),
            row.get("location_type"),
            str(row.get("country") or "")[:2].upper() or None,
            row.get("region"),
            row.get("district"),
            numeric_value(row.get("latitude")),
            numeric_value(row.get("longitude")),
            row.get("created_at"),
            row.get("updated_at"),
        ),
    )


def upsert_currency(cursor: Any, code: str | None) -> None:
    if not code:
        return
    cursor.execute(
        """
        INSERT INTO currencies (currency_code, currency_name, symbol)
        VALUES (%s, %s, %s)
        ON CONFLICT (currency_code) DO NOTHING
        """,
        (code, code, code),
    )


def upsert_place(cursor: Any, row: dict, place_type_id: int, location_id: int | None) -> int:
    return fetch_one_id(
        cursor,
        """
        INSERT INTO places (
            place_type_id, location_id, canonical_name, short_description,
            latitude, longitude, address, phone, email, website, booking_url,
            is_active, created_at, updated_at
        )
        VALUES (
            %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
            COALESCE(%s, TRUE), COALESCE(%s, NOW()), COALESCE(%s, NOW())
        )
        ON CONFLICT (place_type_id, location_id, canonical_name) DO UPDATE SET
            short_description = EXCLUDED.short_description,
            latitude = COALESCE(EXCLUDED.latitude, places.latitude),
            longitude = COALESCE(EXCLUDED.longitude, places.longitude),
            address = COALESCE(EXCLUDED.address, places.address),
            phone = COALESCE(EXCLUDED.phone, places.phone),
            email = COALESCE(EXCLUDED.email, places.email),
            website = COALESCE(EXCLUDED.website, places.website),
            booking_url = COALESCE(EXCLUDED.booking_url, places.booking_url),
            is_active = EXCLUDED.is_active,
            updated_at = NOW()
        RETURNING place_id
        """,
        (
            place_type_id,
            location_id,
            row.get("canonical_name"),
            row.get("short_description"),
            numeric_value(row.get("latitude")),
            numeric_value(row.get("longitude")),
            row.get("address"),
            row.get("phone"),
            row.get("email"),
            row.get("website"),
            row.get("booking_url"),
            row.get("is_active"),
            row.get("created_at"),
            row.get("updated_at"),
        ),
    )


def upsert_place_source(cursor: Any, row: dict, place_id: int, source_id: int) -> int:
    return fetch_one_id(
        cursor,
        """
        INSERT INTO place_source_records (
            place_id, source_id, source_place_id, source_url, source_name,
            source_category, latitude, longitude, star_rating, review_score,
            review_count, ranking_position, ranking_total, ranking_text,
            ranking_category, popularity_score, is_active, first_scraped_at, last_scraped_at,
            raw_json, created_at, updated_at
        )
        VALUES (
            %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
            %s, %s, %s, %s, %s, COALESCE(%s, TRUE),
            COALESCE(%s, NOW()), COALESCE(%s, NOW()),
            %s::jsonb, COALESCE(%s, NOW()), COALESCE(%s, NOW())
        )
        ON CONFLICT (source_id, source_place_id) DO UPDATE SET
            place_id = EXCLUDED.place_id,
            source_url = EXCLUDED.source_url,
            source_name = EXCLUDED.source_name,
            source_category = EXCLUDED.source_category,
            latitude = EXCLUDED.latitude,
            longitude = EXCLUDED.longitude,
            star_rating = EXCLUDED.star_rating,
            review_score = EXCLUDED.review_score,
            review_count = EXCLUDED.review_count,
            ranking_position = EXCLUDED.ranking_position,
            ranking_total = EXCLUDED.ranking_total,
            ranking_text = EXCLUDED.ranking_text,
            ranking_category = EXCLUDED.ranking_category,
            popularity_score = EXCLUDED.popularity_score,
            is_active = EXCLUDED.is_active,
            last_scraped_at = EXCLUDED.last_scraped_at,
            raw_json = EXCLUDED.raw_json,
            updated_at = NOW()
        RETURNING place_source_id
        """,
        (
            place_id,
            source_id,
            text_limit(row.get("source_place_id"), 150),
            row.get("source_url"),
            row.get("source_name"),
            text_limit(row.get("source_category"), 150),
            numeric_value(row.get("latitude")),
            numeric_value(row.get("longitude")),
            bounded_numeric_value(row.get("star_rating"), 0, 5),
            bounded_numeric_value(row.get("review_score"), 0, 10),
            bounded_int_value(row.get("review_count"), 0, 1_000_000) or 0,
            int_value(row.get("ranking_position")),
            int_value(row.get("ranking_total")),
            row.get("ranking_text"),
            text_limit(row.get("ranking_category"), 200),
            numeric_value(row.get("popularity_score")),
            row.get("is_active"),
            row.get("created_at"),
            row.get("last_scraped_at"),
            db_value(row.get("raw_json")) or "{}",
            row.get("created_at"),
            row.get("updated_at"),
        ),
    )


def save_to_postgres(tables: dict[str, list[dict]]) -> None:
    if psycopg is None:
        print("PostgreSQL save skipped: psycopg is not installed.")
        return

    url = database_url()
    if not url:
        print("PostgreSQL save skipped: database settings are missing.")
        return

    ensure_database_exists()

    with psycopg.connect(url) as connection:
        create_database_tables(connection)
        with connection.cursor() as cursor:
            source_ids: dict[str, int] = {}
            for row in tables.get("sources", []):
                source_ids[str(row.get("source_id"))] = upsert_source(cursor, row)

            place_type_ids: dict[str, int] = {}
            for row in tables.get("place_types", []):
                place_type_ids[str(row.get("place_type_id"))] = upsert_place_type(cursor, row)

            location_ids: dict[str, int] = {}
            pending_locations = list(tables.get("locations", []))
            while pending_locations:
                remaining = []
                progressed = False
                for row in pending_locations:
                    parent_key = row.get("parent_location_id")
                    if parent_key and str(parent_key) not in location_ids:
                        remaining.append(row)
                        continue
                    location_ids[str(row.get("location_id"))] = upsert_location(
                        cursor,
                        row,
                        location_ids.get(str(parent_key)) if parent_key else None,
                    )
                    progressed = True
                if not progressed:
                    raise RuntimeError("Could not resolve location parent relationships.")
                pending_locations = remaining

            for rows in [
                tables.get("place_source_records", []),
                tables.get("availability_offers", []),
                tables.get("attractions", []),
            ]:
                for row in rows:
                    upsert_currency(cursor, currency_code(row.get("currency")))

            place_ids: dict[str, int] = {}
            for row in tables.get("places", []):
                old_place_id = str(row.get("place_id"))
                place_ids[old_place_id] = upsert_place(
                    cursor,
                    row,
                    place_type_ids[str(row.get("place_type_id"))],
                    location_ids.get(str(row.get("location_id"))),
                )

            source_code_id = source_ids.get("booking") or next(iter(source_ids.values()))
            place_source_ids: dict[str, int] = {}
            place_id_to_source_id: dict[str, int] = {}
            for row in tables.get("place_source_records", []):
                old_place_source_id = str(row.get("place_source_id"))
                old_place_id = str(row.get("place_id"))
                row_source_id = str(row.get("source_id") or "booking")
                place_source_id = upsert_place_source(
                    cursor,
                    row,
                    place_ids[old_place_id],
                    source_ids.get(row_source_id, source_code_id),
                )
                place_source_ids[old_place_source_id] = place_source_id
                place_id_to_source_id[old_place_id] = place_source_id

            for row in tables.get("accommodations", []):
                place_source_id = place_source_ids.get(str(row.get("place_source_id"))) or place_id_to_source_id.get(str(row.get("place_id")))
                if not place_source_id:
                    continue
                cursor.execute(
                    """
                    INSERT INTO accommodation_source_details (
                        place_source_id, checkin_from, checkin_until, checkout_from,
                        checkout_until, pets_allowed, children_allowed, beachfront,
                        distance_to_beach_m, license_number, airport_shuttle,
                        parking_available, breakfast_available, breakfast_type,
                        property_class, chain_name, year_opened, year_renovated,
                        raw_json, created_at, updated_at
                    )
                    VALUES (
                        %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
                        %s, %s, %s, %s, %s, %s::jsonb, COALESCE(%s, NOW()),
                        COALESCE(%s, NOW())
                    )
                    ON CONFLICT (place_source_id) DO UPDATE SET
                        checkin_from = EXCLUDED.checkin_from,
                        checkin_until = EXCLUDED.checkin_until,
                        checkout_from = EXCLUDED.checkout_from,
                        checkout_until = EXCLUDED.checkout_until,
                        pets_allowed = EXCLUDED.pets_allowed,
                        children_allowed = EXCLUDED.children_allowed,
                        beachfront = EXCLUDED.beachfront,
                        distance_to_beach_m = EXCLUDED.distance_to_beach_m,
                        license_number = EXCLUDED.license_number,
                        airport_shuttle = EXCLUDED.airport_shuttle,
                        parking_available = EXCLUDED.parking_available,
                        breakfast_available = EXCLUDED.breakfast_available,
                        breakfast_type = EXCLUDED.breakfast_type,
                        property_class = EXCLUDED.property_class,
                        chain_name = EXCLUDED.chain_name,
                        year_opened = EXCLUDED.year_opened,
                        year_renovated = EXCLUDED.year_renovated,
                        raw_json = EXCLUDED.raw_json,
                        updated_at = NOW()
                    """,
                    (
                        place_source_id,
                        time_value(row.get("checkin_from") or row.get("checkin_time")),
                        time_value(row.get("checkin_until")),
                        time_value(row.get("checkout_from")),
                        time_value(row.get("checkout_until") or row.get("checkout_time")),
                        bool_value(row.get("pets_allowed")),
                        bool_value(row.get("children_allowed") if row.get("children_allowed") is not None else row.get("child_friendly")),
                        bool_value(row.get("beachfront")),
                        int_value(row.get("distance_to_beach_m")),
                        row.get("license_number"),
                        bool_value(row.get("airport_shuttle")),
                        bool_value(row.get("parking_available")),
                        bool_value(row.get("breakfast_available")),
                        text_limit(row.get("breakfast_type"), 150),
                        text_limit(row.get("property_class"), 100),
                        text_limit(row.get("chain_name"), 200),
                        int_value(row.get("year_opened")),
                        int_value(row.get("year_renovated")),
                        db_value(row.get("raw_json")) or "{}",
                        row.get("created_at"),
                        row.get("updated_at"),
                    ),
                )

            for row in tables.get("attractions", []):
                place_source_id = place_source_ids.get(str(row.get("place_source_id"))) or place_id_to_source_id.get(str(row.get("place_id")))
                if not place_source_id:
                    continue
                upsert_currency(cursor, currency_code(row.get("currency_code") or row.get("currency")))
                cursor.execute(
                    """
                    INSERT INTO attraction_source_details (
                        place_source_id, attraction_category, attraction_subcategory,
                        recommended_duration, duration_minutes, ticket_required,
                        booking_available, price_from, currency_code, family_friendly,
                        accessibility_info, raw_json, created_at, updated_at
                    )
                    VALUES (
                        %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
                        %s::jsonb, COALESCE(%s, NOW()), COALESCE(%s, NOW())
                    )
                    ON CONFLICT (place_source_id) DO UPDATE SET
                        attraction_category = EXCLUDED.attraction_category,
                        attraction_subcategory = EXCLUDED.attraction_subcategory,
                        recommended_duration = EXCLUDED.recommended_duration,
                        duration_minutes = EXCLUDED.duration_minutes,
                        ticket_required = EXCLUDED.ticket_required,
                        booking_available = EXCLUDED.booking_available,
                        price_from = EXCLUDED.price_from,
                        currency_code = EXCLUDED.currency_code,
                        family_friendly = EXCLUDED.family_friendly,
                        accessibility_info = EXCLUDED.accessibility_info,
                        raw_json = EXCLUDED.raw_json,
                        updated_at = NOW()
                    """,
                    (
                        place_source_id,
                        text_limit(row.get("attraction_category") or row.get("attraction_type"), 200),
                        text_limit(row.get("attraction_subcategory"), 200),
                        row.get("recommended_duration"),
                        int_value(row.get("duration_minutes")),
                        bool_value(row.get("ticket_required")),
                        bool_value(row.get("booking_available") if row.get("booking_available") is not None else row.get("booking_required")),
                        numeric_value(row.get("price_from") if row.get("price_from") is not None else row.get("entry_fee")),
                        currency_code(row.get("currency_code") or row.get("currency")),
                        bool_value(row.get("family_friendly")),
                        row.get("accessibility_info"),
                        db_value(row.get("raw_json")) or "{}",
                        row.get("created_at"),
                        row.get("updated_at"),
                    ),
                )

            for row in tables.get("restaurants", []):
                place_source_id = place_source_ids.get(str(row.get("place_source_id"))) or place_id_to_source_id.get(str(row.get("place_id")))
                if not place_source_id:
                    continue
                cursor.execute(
                    """
                    INSERT INTO restaurant_source_details (
                        place_source_id, price_range, reservation_available,
                        delivery_available, takeaway_available, seating_available,
                        outdoor_seating, raw_json, created_at, updated_at
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s::jsonb, COALESCE(%s, NOW()), COALESCE(%s, NOW()))
                    ON CONFLICT (place_source_id) DO UPDATE SET
                        price_range = EXCLUDED.price_range,
                        reservation_available = EXCLUDED.reservation_available,
                        delivery_available = EXCLUDED.delivery_available,
                        takeaway_available = EXCLUDED.takeaway_available,
                        seating_available = EXCLUDED.seating_available,
                        outdoor_seating = EXCLUDED.outdoor_seating,
                        raw_json = EXCLUDED.raw_json,
                        updated_at = NOW()
                    """,
                    (
                        place_source_id,
                        text_limit(row.get("price_range") or row.get("price_level"), 100),
                        bool_value(row.get("reservation_available")),
                        bool_value(row.get("delivery_available") if row.get("delivery_available") is not None else row.get("delivery")),
                        bool_value(row.get("takeaway_available") if row.get("takeaway_available") is not None else row.get("takeaway")),
                        bool_value(row.get("seating_available")),
                        bool_value(row.get("outdoor_seating")),
                        db_value(row.get("raw_json")) or "{}",
                        row.get("created_at"),
                        row.get("updated_at"),
                    ),
                )

            amenity_ids: dict[str, int] = {}
            for row in tables.get("amenities", []):
                amenity_ids[str(row.get("amenity_id"))] = fetch_one_id(
                    cursor,
                    """
                    INSERT INTO amenities (amenity_name, amenity_category, created_at, updated_at)
                    VALUES (%s, %s, COALESCE(%s, NOW()), COALESCE(%s, NOW()))
                    ON CONFLICT (amenity_name, amenity_category) DO UPDATE SET updated_at = NOW()
                    RETURNING amenity_id
                    """,
                    (
                        text_limit(row.get("amenity_name"), 200),
                        text_limit(row.get("amenity_category"), 100),
                        row.get("created_at"),
                        row.get("updated_at"),
                    ),
                )

            for row in tables.get("place_amenities", []):
                place_source_id = place_id_to_source_id.get(str(row.get("place_id")))
                amenity_id = amenity_ids.get(str(row.get("amenity_id")))
                if not place_source_id or not amenity_id:
                    continue
                cursor.execute(
                    """
                    INSERT INTO place_source_amenities (
                        place_source_id, amenity_id, is_available, additional_info,
                        created_at, updated_at
                    )
                    VALUES (%s, %s, COALESCE(%s, TRUE), %s, COALESCE(%s, NOW()), COALESCE(%s, NOW()))
                    ON CONFLICT (place_source_id, amenity_id) DO UPDATE SET
                        is_available = EXCLUDED.is_available,
                        additional_info = EXCLUDED.additional_info,
                        updated_at = NOW()
                    """,
                    (
                        place_source_id,
                        amenity_id,
                        row.get("is_available"),
                        row.get("additional_info"),
                        row.get("created_at"),
                        row.get("updated_at"),
                    ),
                )

            for row in tables.get("images", []):
                place_source_id = place_id_to_source_id.get(str(row.get("place_id")))
                if not place_source_id:
                    continue
                cursor.execute(
                    """
                    INSERT INTO images (
                        place_source_id, source_image_id, image_url, thumbnail_url,
                        image_type, caption, display_order, is_primary, image_hash,
                        width_pixels, height_pixels, raw_json, created_at
                    )
                    VALUES (
                        %s, %s, %s, %s, %s, %s, %s, COALESCE(%s, FALSE), %s,
                        %s, %s, %s::jsonb, COALESCE(%s, NOW())
                    )
                    ON CONFLICT (place_source_id, image_hash) DO UPDATE SET
                        source_image_id = EXCLUDED.source_image_id,
                        image_url = EXCLUDED.image_url,
                        thumbnail_url = EXCLUDED.thumbnail_url,
                        image_type = EXCLUDED.image_type,
                        caption = EXCLUDED.caption,
                        display_order = EXCLUDED.display_order,
                        is_primary = EXCLUDED.is_primary,
                        width_pixels = EXCLUDED.width_pixels,
                        height_pixels = EXCLUDED.height_pixels,
                        raw_json = EXCLUDED.raw_json
                    """,
                    (
                        place_source_id,
                        text_limit(row.get("source_image_id"), 150),
                        row.get("image_url"),
                        row.get("thumbnail_url"),
                        row.get("image_type"),
                        row.get("caption"),
                        int_value(row.get("display_order")),
                        row.get("is_primary"),
                        row.get("image_hash"),
                        int_value(row.get("width_pixels")),
                        int_value(row.get("height_pixels")),
                        db_value(row.get("raw_json")) or "{}",
                        row.get("created_at"),
                    ),
                )

            reviewer_ids: dict[str, int] = {}
            for row in tables.get("reviewers", []):
                source_reviewer_id = text_limit(row.get("source_reviewer_id"), 150)
                row_source_id = str(row.get("source_id") or "booking")
                reviewer_ids[str(row.get("reviewer_id"))] = fetch_one_id(
                    cursor,
                    """
                    INSERT INTO reviewers (
                        source_id, source_reviewer_id, reviewer_name, username,
                        country_code, country_name, reviewer_level, profile_url,
                        profile_image_url, contribution_count, helpful_vote_count,
                        raw_json, created_at, updated_at
                    )
                    VALUES (
                        %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
                        %s::jsonb, COALESCE(%s, NOW()), COALESCE(%s, NOW())
                    )
                    ON CONFLICT (source_id, source_reviewer_id) DO UPDATE SET
                        reviewer_name = EXCLUDED.reviewer_name,
                        username = EXCLUDED.username,
                        country_code = EXCLUDED.country_code,
                        country_name = EXCLUDED.country_name,
                        reviewer_level = EXCLUDED.reviewer_level,
                        profile_url = EXCLUDED.profile_url,
                        profile_image_url = EXCLUDED.profile_image_url,
                        contribution_count = EXCLUDED.contribution_count,
                        helpful_vote_count = EXCLUDED.helpful_vote_count,
                        raw_json = EXCLUDED.raw_json,
                        updated_at = NOW()
                    RETURNING reviewer_id
                    """,
                    (
                        source_ids.get(row_source_id, source_code_id),
                        source_reviewer_id,
                        text_limit(row.get("reviewer_name"), 200),
                        text_limit(row.get("username"), 200),
                        str(row.get("country_code") or row.get("country") or "")[:2].upper() or None,
                        text_limit(row.get("country_name") or row.get("country"), 150),
                        text_limit(row.get("reviewer_level"), 100),
                        row.get("profile_url") or row.get("profile_image"),
                        row.get("profile_image_url") or row.get("profile_image"),
                        int_value(row.get("contribution_count")),
                        int_value(row.get("helpful_vote_count")),
                        db_value(row.get("raw_json")) or "{}",
                        row.get("created_at"),
                        row.get("updated_at"),
                    ),
                )

            review_ids: dict[str, int] = {}
            for row in tables.get("reviews", []):
                place_source_id = place_source_ids.get(str(row.get("place_source_id")))
                if not place_source_id:
                    continue
                reviewer_id = reviewer_ids.get(str(row.get("reviewer_id")))
                review_date = date_value(row.get("review_date")) or datetime.utcnow().date()
                source_review_id = text_limit(row.get("source_review_id"), 150)
                cursor.execute(
                    """
                    INSERT INTO reviews (
                        place_source_id, reviewer_id, source_review_id, review_title,
                        review_text, positive_text, negative_text, review_score,
                        rating_scale, travel_type, trip_type, country_code, room_name,
                        visit_date, stay_date, review_date, verified_stay, is_verified,
                        helpful_votes, language_code, original_language_code,
                        is_machine_translated, source_url, raw_json, created_at, updated_at
                    )
                    VALUES (
                        %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
                        %s, %s, %s, %s, %s, %s, COALESCE(%s, 0), %s, %s,
                        %s, %s, %s::jsonb,
                        COALESCE(%s, NOW()), COALESCE(%s, NOW())
                    )
                    ON CONFLICT (place_source_id, source_review_id) DO UPDATE SET
                        reviewer_id = COALESCE(EXCLUDED.reviewer_id, reviews.reviewer_id),
                        review_title = COALESCE(EXCLUDED.review_title, reviews.review_title),
                        review_text = COALESCE(EXCLUDED.review_text, reviews.review_text),
                        positive_text = COALESCE(EXCLUDED.positive_text, reviews.positive_text),
                        negative_text = COALESCE(EXCLUDED.negative_text, reviews.negative_text),
                        review_score = COALESCE(EXCLUDED.review_score, reviews.review_score),
                        rating_scale = COALESCE(EXCLUDED.rating_scale, reviews.rating_scale),
                        travel_type = COALESCE(EXCLUDED.travel_type, reviews.travel_type),
                        trip_type = COALESCE(EXCLUDED.trip_type, reviews.trip_type),
                        room_name = COALESCE(EXCLUDED.room_name, reviews.room_name),
                        visit_date = COALESCE(EXCLUDED.visit_date, reviews.visit_date),
                        stay_date = COALESCE(EXCLUDED.stay_date, reviews.stay_date),
                        review_date = COALESCE(EXCLUDED.review_date, reviews.review_date),
                        verified_stay = COALESCE(EXCLUDED.verified_stay, reviews.verified_stay),
                        is_verified = COALESCE(EXCLUDED.is_verified, reviews.is_verified),
                        helpful_votes = COALESCE(EXCLUDED.helpful_votes, reviews.helpful_votes),
                        language_code = COALESCE(EXCLUDED.language_code, reviews.language_code),
                        original_language_code = COALESCE(EXCLUDED.original_language_code, reviews.original_language_code),
                        is_machine_translated = COALESCE(EXCLUDED.is_machine_translated, reviews.is_machine_translated),
                        source_url = COALESCE(EXCLUDED.source_url, reviews.source_url),
                        raw_json = COALESCE(EXCLUDED.raw_json, reviews.raw_json),
                        updated_at = NOW()
                    RETURNING review_id
                    """,
                    (
                        place_source_id,
                        reviewer_id,
                        source_review_id,
                        row.get("review_title"),
                        row.get("review_text"),
                        row.get("positive_text"),
                        row.get("negative_text"),
                        bounded_numeric_value(row.get("review_score"), 0, 10),
                        bounded_numeric_value(row.get("rating_scale"), 0, 10),
                        text_limit(row.get("travel_type"), 100),
                        text_limit(row.get("trip_type"), 100),
                        None,
                        row.get("room_name"),
                        date_value(row.get("visit_date")),
                        date_value(row.get("stay_date")),
                        review_date,
                        row.get("verified_stay"),
                        row.get("is_verified"),
                        int_value(row.get("helpful_votes")),
                        row.get("language_code") or row.get("language"),
                        row.get("original_language_code"),
                        row.get("is_machine_translated"),
                        row.get("source_url"),
                        db_value(row.get("raw_json")) or "{}",
                        row.get("created_at"),
                        row.get("updated_at"),
                    ),
                )
                inserted = cursor.fetchone()
                if inserted:
                    review_ids[str(row.get("review_id"))] = int(inserted[0])
                else:
                    cursor.execute(
                        """
                        SELECT review_id FROM reviews
                        WHERE place_source_id = %s AND source_review_id = %s
                        """,
                        (place_source_id, source_review_id),
                    )
                    fetched = cursor.fetchone()
                    if fetched:
                        review_ids[str(row.get("review_id"))] = int(fetched[0])

            for row in tables.get("review_category_scores", []):
                review_id = review_ids.get(str(row.get("review_id")))
                score = bounded_numeric_value(row.get("score"), 0, 10)
                if not review_id or not row.get("category_name") or score is None:
                    continue
                cursor.execute(
                    """
                    INSERT INTO review_category_scores (
                        review_id, category_name, score, rating_scale, created_at
                    )
                    VALUES (%s, %s, %s, %s, COALESCE(%s, NOW()))
                    ON CONFLICT (review_id, category_name) DO UPDATE SET
                        score = EXCLUDED.score,
                        rating_scale = EXCLUDED.rating_scale
                    """,
                    (
                        review_id,
                        text_limit(row.get("category_name"), 100),
                        score,
                        bounded_numeric_value(row.get("rating_scale"), 0, 10),
                        row.get("created_at"),
                    ),
                )

            for row in tables.get("review_responses", []):
                review_id = review_ids.get(str(row.get("review_id")))
                if not review_id or not row.get("response_text"):
                    continue
                source_response_id = text_limit(row.get("source_response_id"), 150)
                cursor.execute(
                    """
                    INSERT INTO review_responses (
                        review_id, source_response_id, responder_name, responder_role,
                        response_text, response_date, raw_json, created_at, updated_at
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s::jsonb, COALESCE(%s, NOW()), COALESCE(%s, NOW()))
                    ON CONFLICT (review_id, source_response_id) DO UPDATE SET
                        responder_name = EXCLUDED.responder_name,
                        responder_role = EXCLUDED.responder_role,
                        response_text = EXCLUDED.response_text,
                        response_date = EXCLUDED.response_date,
                        raw_json = EXCLUDED.raw_json,
                        updated_at = NOW()
                    """,
                    (
                        review_id,
                        source_response_id,
                        text_limit(row.get("responder_name"), 200),
                        text_limit(row.get("responder_role"), 100),
                        row.get("response_text"),
                        date_value(row.get("response_date")),
                        db_value(row.get("raw_json")) or "{}",
                        row.get("created_at"),
                        row.get("updated_at"),
                    ),
                )

            run_row = (tables.get("scraping_runs") or [{}])[0]
            run_source_id = str(run_row.get("source_id") or "booking")
            scraping_run_id = fetch_one_id(
                cursor,
                """
                INSERT INTO scraping_runs (
                    source_id, run_type, entity_type, status, started_at, completed_at,
                    pages_total, pages_success, pages_successful, pages_failed,
                    records_found, records_new, records_updated, errors_count,
                    stop_reason, created_at
                )
                VALUES (
                    %s, %s, %s, %s, COALESCE(%s, NOW()), %s, %s, %s, %s, %s,
                    %s, %s, %s, %s, %s, COALESCE(%s, NOW())
                )
                RETURNING scraping_run_id
                """,
                (
                    source_ids.get(run_source_id, source_code_id),
                    run_row.get("run_type") or "booking_collection",
                    run_row.get("entity_type"),
                    run_row.get("status") or "completed",
                    run_row.get("started_at"),
                    run_row.get("completed_at"),
                    int_value(run_row.get("pages_total")) or 0,
                    int_value(run_row.get("pages_successful") or run_row.get("places_found")) or 0,
                    int_value(run_row.get("pages_successful") or run_row.get("places_found")) or 0,
                    int_value(run_row.get("pages_failed")) or 0,
                    int_value(run_row.get("records_found") or run_row.get("places_found") or run_row.get("reviews_found")) or 0,
                    int_value(run_row.get("records_new") or run_row.get("places_inserted") or run_row.get("reviews_inserted")) or 0,
                    int_value(run_row.get("records_updated") or run_row.get("places_updated")) or 0,
                    int_value(run_row.get("error_count")) or 0,
                    run_row.get("stop_reason"),
                    run_row.get("created_at"),
                ),
            )

            for row in tables.get("availability_offers", []):
                place_source_id = place_source_ids.get(str(row.get("place_source_id")))
                if not place_source_id:
                    continue
                checkin = date_value(row.get("checkin"))
                checkout = date_value(row.get("checkout"))
                nights = (checkout - checkin).days if checkin and checkout else 1
                cursor.execute(
                    """
                    INSERT INTO availability_offers (
                        place_source_id, checkin_date, checkout_date, nights,
                        adults, children, rooms_requested, currency_code,
                        original_price, final_price, available, scraped_at, created_at
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, COALESCE(%s, FALSE), COALESCE(%s, NOW()), NOW())
                    """,
                    (
                        place_source_id,
                        checkin,
                        checkout,
                        nights,
                        int_value(row.get("adults")) or ADULTS,
                        int_value(row.get("children")) or CHILDREN,
                        int_value(row.get("rooms")) or ROOMS,
                        currency_code(row.get("currency")),
                        numeric_value(row.get("price")),
                        numeric_value(row.get("price")),
                        row.get("available"),
                        row.get("scraped_at"),
                    ),
                )

            for row in tables.get("place_policies", []):
                place_source_id = place_source_ids.get(str(row.get("place_source_id"))) or place_id_to_source_id.get(str(row.get("place_id")))
                if not place_source_id:
                    continue
                cursor.execute(
                    """
                    INSERT INTO place_policies (
                        place_source_id, policy_type, policy_text, effective_from,
                        effective_to, created_at, updated_at
                    )
                    VALUES (%s, %s, %s, %s, %s, COALESCE(%s, NOW()), COALESCE(%s, NOW()))
                    """,
                    (
                        place_source_id,
                        row.get("policy_type"),
                        row.get("policy_text"),
                        date_value(row.get("effective_from")),
                        date_value(row.get("effective_to")),
                        row.get("created_at"),
                        row.get("updated_at"),
                    ),
                )

            for row in tables.get("operating_hours", []):
                place_source_id = place_source_ids.get(str(row.get("place_source_id")))
                day_of_week = int_value(row.get("day_of_week"))
                if not place_source_id or day_of_week is None:
                    continue
                cursor.execute(
                    """
                    INSERT INTO operating_hours (
                        place_source_id, day_of_week, open_time, close_time,
                        is_closed, is_24_hours, raw_text, created_at
                    )
                    VALUES (%s, %s, %s, %s, COALESCE(%s, FALSE), COALESCE(%s, FALSE), %s, COALESCE(%s, NOW()))
                    ON CONFLICT (place_source_id, day_of_week) DO UPDATE SET
                        open_time = EXCLUDED.open_time,
                        close_time = EXCLUDED.close_time,
                        is_closed = EXCLUDED.is_closed,
                        is_24_hours = EXCLUDED.is_24_hours,
                        raw_text = EXCLUDED.raw_text
                    """,
                    (
                        place_source_id,
                        day_of_week,
                        time_value(row.get("open_time")),
                        time_value(row.get("close_time")),
                        bool_value(row.get("is_closed")),
                        bool_value(row.get("is_24_hours")),
                        row.get("raw_text"),
                        row.get("created_at"),
                    ),
                )

        connection.commit()

    print("PostgreSQL save completed using standardized BIGINT schema.")
    for table_name, rows in tables.items():
        print(f'Rows processed from "{table_name}": {len(rows)}')


def fetch_existing_review_state_by_hotel(
    hotels: list[dict],
) -> dict[str, ReviewIncrementState]:
    if psycopg is None:
        return {}
    url = database_url()
    if not url:
        return {}

    ensure_database_exists()
    result: dict[str, ReviewIncrementState] = {}
    try:
        with psycopg.connect(url) as connection:
            create_database_tables(connection)
            with connection.cursor() as cursor:
                for hotel in hotels:
                    hotel_id = hotel.get("hotel_id")
                    if hotel_id in (None, ""):
                        continue
                    hotel_id_text = str(hotel_id)
                    cursor.execute(
                        """
                        SELECT r.source_review_id, r.review_date
                        FROM reviews r
                        JOIN place_source_records psr ON psr.place_source_id = r.place_source_id
                        JOIN sources s ON s.source_id = psr.source_id
                        WHERE s.source_code = 'BOOKING' AND psr.source_place_id = %s
                        """,
                        (hotel_id_text,),
                    )
                    rows = cursor.fetchall()
                    source_review_ids = {str(row[0]) for row in rows if row and row[0]}
                    parsed_dates = [
                        parsed
                        for row in rows
                        if len(row) > 1
                        for parsed in [parse_date(row[1])]
                        if parsed is not None
                    ]
                    result[hotel_id_text] = {
                        "source_review_ids": source_review_ids,
                        "newest_review_date": max(parsed_dates).isoformat() if parsed_dates else None,
                    }
            connection.commit()
    except Exception as error:
        print("Incremental review check skipped:", error)
        return {}

    print(
        "Existing review IDs loaded from PostgreSQL: "
        f"{sum(len(v.get('source_review_ids', set())) for v in result.values())}"
    )
    return result


def fetch_existing_review_ids_by_hotel(
    hotels: list[dict],
) -> dict[str, set[str]]:
    state_by_hotel = fetch_existing_review_state_by_hotel(hotels)
    return {
        hotel_id: state.get("source_review_ids", set())
        for hotel_id, state in state_by_hotel.items()
    }


def fetch_existing_review_ids_by_place_source_ids(
    place_source_ids: list[str],
) -> dict[str, set[str]]:
    if psycopg is None:
        return {}
    url = database_url()
    if not url:
        return {}

    ensure_database_exists()
    result: dict[str, set[str]] = {place_source_id: set() for place_source_id in place_source_ids if place_source_id}
    if not result:
        return {}

    def source_place_id_from_legacy(value: str) -> str:
        return value.rsplit(":", 1)[-1]

    try:
        with psycopg.connect(url) as connection:
            create_database_tables(connection)
            with connection.cursor() as cursor:
                for legacy_place_source_id in result:
                    cursor.execute(
                        """
                        SELECT r.source_review_id
                        FROM reviews r
                        JOIN place_source_records psr ON psr.place_source_id = r.place_source_id
                        JOIN sources s ON s.source_id = psr.source_id
                        WHERE s.source_code = 'BOOKING' AND psr.source_place_id = %s
                        """,
                        (source_place_id_from_legacy(legacy_place_source_id),),
                    )
                    result[legacy_place_source_id] = {
                        str(row[0])
                        for row in cursor.fetchall()
                        if row and row[0] not in (None, "")
                    }
            connection.commit()
    except Exception as error:
        print("Generic incremental review check skipped:", error)
        return {}

    print(
        "Existing generic review IDs loaded from PostgreSQL: "
        f"{sum(len(values) for values in result.values())}"
    )
    return result


def fetch_known_places_for_reviews(source_code: str) -> tuple[list[dict], list[dict]]:
    if psycopg is None:
        print("Known place load skipped: psycopg is not installed.")
        return [], []

    url = database_url()
    if not url:
        print("Known place load skipped: database settings are missing.")
        return [], []

    ensure_database_exists()
    source_code = source_code.strip().upper()
    source_id = source_code.lower()
    hotels: list[dict] = []
    attractions: list[dict] = []

    try:
        with psycopg.connect(url) as connection:
            create_database_tables(connection)
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT
                        psr.source_place_id,
                        psr.source_url,
                        psr.source_name,
                        psr.source_category,
                        psr.raw_json,
                        p.canonical_name,
                        pt.type_group
                    FROM place_source_records psr
                    JOIN sources s ON s.source_id = psr.source_id
                    JOIN places p ON p.place_id = psr.place_id
                    JOIN place_types pt ON pt.place_type_id = p.place_type_id
                    WHERE s.source_code = %s
                      AND psr.source_url IS NOT NULL
                      AND psr.is_active = TRUE
                    ORDER BY pt.type_group, psr.source_name
                    """,
                    (source_code,),
                )
                rows = cursor.fetchall()
            connection.commit()
    except Exception as error:
        print("Known place load failed:", error)
        return [], []

    for row in rows:
        (
            source_place_id,
            source_url,
            source_name,
            source_category,
            raw_json,
            canonical_name,
            type_group,
        ) = row
        raw = raw_json if isinstance(raw_json, dict) else {}
        if isinstance(raw_json, str):
            try:
                raw = json.loads(raw_json)
            except json.JSONDecodeError:
                raw = {}

        place = {
            **raw,
            "source": raw.get("source") or source_id,
            "name": raw.get("name") or source_name or canonical_name,
            "property_url": raw.get("property_url") or source_url,
            "source_place_id": raw.get("source_place_id") or str(source_place_id),
        }

        if type_group == "Accommodation":
            place["hotel_id"] = raw.get("hotel_id") or str(source_place_id)
            if source_id == "tripadvisor":
                place["tripadvisor_id"] = raw.get("tripadvisor_id") or str(source_place_id)
            place["accommodation_type_id"] = raw.get("accommodation_type_id") or source_category
            place["sold_out"] = False
            hotels.append(place)
            continue

        if type_group in {"Attraction", "Activity", "Restaurant"}:
            place["attraction_id"] = raw.get("attraction_id") or str(source_place_id)
            if source_id == "tripadvisor":
                place["tripadvisor_id"] = raw.get("tripadvisor_id") or str(source_place_id)
                place["place_id"] = raw.get("place_id") or f"tripadvisor:attraction:place:{source_place_id}"
                place["place_source_id"] = (
                    raw.get("place_source_id")
                    or f"tripadvisor:attraction:listing:{source_place_id}"
                )
            attractions.append(place)

    print(
        f"Known {source_code} places loaded from PostgreSQL: "
        f"{len(hotels)} hotels, {len(attractions)} attractions"
    )
    return hotels, attractions


def fetch_known_booking_places_for_reviews() -> tuple[list[dict], list[dict]]:
    return fetch_known_places_for_reviews("BOOKING")


def fetch_known_tripadvisor_places_for_reviews() -> tuple[list[dict], list[dict]]:
    return fetch_known_places_for_reviews("TRIPADVISOR")
