-- Jozani 2.0 source-aware Tripadvisor review support.
-- Non-destructive migration: extend existing tables and create missing source detail tables.

CREATE UNIQUE INDEX IF NOT EXISTS idx_sources_source_name_unique ON sources(source_name);

ALTER TABLE places ADD COLUMN IF NOT EXISTS latitude NUMERIC(10,7);
ALTER TABLE places ADD COLUMN IF NOT EXISTS longitude NUMERIC(10,7);
ALTER TABLE places ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE place_source_records ADD COLUMN IF NOT EXISTS ranking_total INTEGER;
ALTER TABLE place_source_records ADD COLUMN IF NOT EXISTS ranking_text TEXT;
ALTER TABLE place_source_records ADD COLUMN IF NOT EXISTS ranking_category VARCHAR(200);

ALTER TABLE accommodation_source_details ADD COLUMN IF NOT EXISTS checkin_until TIME;
ALTER TABLE accommodation_source_details ADD COLUMN IF NOT EXISTS checkout_from TIME;
ALTER TABLE accommodation_source_details ADD COLUMN IF NOT EXISTS breakfast_available BOOLEAN;
ALTER TABLE accommodation_source_details ADD COLUMN IF NOT EXISTS property_class VARCHAR(100);
ALTER TABLE accommodation_source_details ADD COLUMN IF NOT EXISTS raw_json JSONB;

CREATE TABLE IF NOT EXISTS attraction_source_details (
    detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_source_id BIGINT NOT NULL UNIQUE REFERENCES place_source_records(place_source_id),
    attraction_category VARCHAR(200),
    attraction_subcategory VARCHAR(200),
    recommended_duration TEXT,
    duration_minutes INTEGER,
    ticket_required BOOLEAN,
    booking_available BOOLEAN,
    price_from NUMERIC(14,2),
    currency_code CHAR(3) REFERENCES currencies(currency_code),
    family_friendly BOOLEAN,
    accessibility_info TEXT,
    raw_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS restaurant_source_details (
    detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_source_id BIGINT NOT NULL UNIQUE REFERENCES place_source_records(place_source_id),
    price_range VARCHAR(100),
    reservation_available BOOLEAN,
    delivery_available BOOLEAN,
    takeaway_available BOOLEAN,
    seating_available BOOLEAN,
    outdoor_seating BOOLEAN,
    raw_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS operating_hours (
    operating_hour_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_source_id BIGINT NOT NULL REFERENCES place_source_records(place_source_id),
    day_of_week SMALLINT NOT NULL,
    open_time TIME,
    close_time TIME,
    is_closed BOOLEAN NOT NULL DEFAULT FALSE,
    is_24_hours BOOLEAN NOT NULL DEFAULT FALSE,
    raw_text TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (place_source_id, day_of_week)
);

ALTER TABLE place_source_amenities ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE images ADD COLUMN IF NOT EXISTS source_image_id VARCHAR(150);
ALTER TABLE images ADD COLUMN IF NOT EXISTS raw_json JSONB;

ALTER TABLE reviewers ALTER COLUMN source_reviewer_id DROP NOT NULL;
ALTER TABLE reviewers ADD COLUMN IF NOT EXISTS username VARCHAR(200);
ALTER TABLE reviewers ADD COLUMN IF NOT EXISTS country_name VARCHAR(150);
ALTER TABLE reviewers ADD COLUMN IF NOT EXISTS profile_url TEXT;
ALTER TABLE reviewers ADD COLUMN IF NOT EXISTS contribution_count INTEGER;
ALTER TABLE reviewers ADD COLUMN IF NOT EXISTS helpful_vote_count INTEGER;
ALTER TABLE reviewers ADD COLUMN IF NOT EXISTS raw_json JSONB;

ALTER TABLE reviews ALTER COLUMN source_review_id DROP NOT NULL;
ALTER TABLE reviews ALTER COLUMN review_date DROP NOT NULL;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS rating_scale NUMERIC(4,2);
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS stay_date DATE;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS trip_type VARCHAR(100);
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS original_language_code VARCHAR(20);
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS is_machine_translated BOOLEAN;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS is_verified BOOLEAN;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS source_url TEXT;

ALTER TABLE review_category_scores ADD COLUMN IF NOT EXISTS rating_scale NUMERIC(4,2);
ALTER TABLE review_responses ADD COLUMN IF NOT EXISTS raw_json JSONB;
ALTER TABLE place_policies ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE scraping_runs ADD COLUMN IF NOT EXISTS entity_type VARCHAR(100);
ALTER TABLE scraping_runs ADD COLUMN IF NOT EXISTS records_found INTEGER;
ALTER TABLE scraping_runs ADD COLUMN IF NOT EXISTS records_new INTEGER;
ALTER TABLE scraping_runs ADD COLUMN IF NOT EXISTS records_updated INTEGER;
ALTER TABLE scraping_runs ADD COLUMN IF NOT EXISTS pages_successful INTEGER;
ALTER TABLE scraping_runs ADD COLUMN IF NOT EXISTS stop_reason TEXT;

CREATE INDEX IF NOT EXISTS idx_source_records_source_place ON place_source_records(source_id, source_place_id);
CREATE INDEX IF NOT EXISTS idx_reviewers_source_reviewer ON reviewers(source_id, source_reviewer_id);
CREATE INDEX IF NOT EXISTS idx_reviews_source_record ON reviews(place_source_id);
CREATE INDEX IF NOT EXISTS idx_reviews_source_review ON reviews(source_review_id);
CREATE INDEX IF NOT EXISTS idx_reviews_date ON reviews(review_date);
CREATE INDEX IF NOT EXISTS idx_review_category_scores_review ON review_category_scores(review_id);
CREATE INDEX IF NOT EXISTS idx_review_responses_review ON review_responses(review_id);
CREATE INDEX IF NOT EXISTS idx_scraping_runs_source_entity_started ON scraping_runs(source_id, entity_type, started_at);
CREATE INDEX IF NOT EXISTS idx_locations_country_code ON locations(country_code);
